# Generated by Django 4.1.3 on 2023-01-20 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daughter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GrandFather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GrandMother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daughter', to='myfamily.grandfather')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daughter', to='myfamily.grandmother')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Son',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brother', models.ManyToManyField(blank=True, to='myfamily.son')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='son', to='myfamily.father')),
                ('grandfather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grandson', to='myfamily.grandfather')),
                ('grandmother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grandson', to='myfamily.grandmother')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='son', to='myfamily.mother')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myfamily.person')),
                ('sister', models.ManyToManyField(blank=True, related_name='brothers', to='myfamily.daughter')),
            ],
        ),
        migrations.AddField(
            model_name='mother',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myfamily.person'),
        ),
        migrations.AddField(
            model_name='grandmother',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myfamily.person'),
        ),
        migrations.AddField(
            model_name='grandfather',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myfamily.person'),
        ),
        migrations.AddField(
            model_name='father',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='son', to='myfamily.grandfather'),
        ),
        migrations.AddField(
            model_name='father',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='son', to='myfamily.grandmother'),
        ),
        migrations.AddField(
            model_name='father',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myfamily.person'),
        ),
        migrations.AddField(
            model_name='daughter',
            name='brother',
            field=models.ManyToManyField(blank=True, related_name='sisters', to='myfamily.son'),
        ),
        migrations.AddField(
            model_name='daughter',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daughter', to='myfamily.father'),
        ),
        migrations.AddField(
            model_name='daughter',
            name='grandfather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granddaughter', to='myfamily.grandfather'),
        ),
        migrations.AddField(
            model_name='daughter',
            name='grandmother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granddaughter', to='myfamily.grandmother'),
        ),
        migrations.AddField(
            model_name='daughter',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daughter', to='myfamily.mother'),
        ),
        migrations.AddField(
            model_name='daughter',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myfamily.person'),
        ),
        migrations.AddField(
            model_name='daughter',
            name='sister',
            field=models.ManyToManyField(blank=True, to='myfamily.daughter'),
        ),
    ]
