# Generated by Django 4.1.3 on 2023-01-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfamily', '0002_alter_daughter_brother_alter_son_grandfather_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daughter',
            name='brother',
        ),
        migrations.AlterField(
            model_name='son',
            name='grandfather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grandson', to='myfamily.grandfather'),
        ),
        migrations.AlterField(
            model_name='son',
            name='sister',
            field=models.ManyToManyField(related_name='brother', to='myfamily.daughter'),
        ),
    ]
