# Generated by Django 4.1.3 on 2023-01-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfamily', '0003_remove_daughter_brother_alter_son_grandfather_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='son',
            name='sister',
            field=models.ManyToManyField(blank=True, related_name='brother', to='myfamily.daughter'),
        ),
    ]
